### ISSUE TITLE
Charts collapse onto themselves when element is resized

### ISSUE THREAD

**Issue by brocococonut** [IBM/carbon-charts#107]
#### I am submitting a...

- [ ] Feature request
- [x] Design defect
- [ ] Source code defect
- [x] Demo/documentation defect
- [ ] Other

### Issue description
Charts fold in on themselves as they don't have any minimum height requirements when resizing in a resizable element

#### Steps to produce the issue
> Go to the demos page and shrink the size of any chart container element vertically using the bottom right hand corner

#### Current behavior
Charts collapse in on themselves

#### Expected behavior
Chart has a minimum height to avoid the above

### Screenshot or recording
![image](https://user-images.githubusercontent.com/6368283/48867162-6592f600-ee29-11e8-80cf-3b73b6ab48ac.png)
![image](https://user-images.githubusercontent.com/6368283/48867173-73e11200-ee29-11e8-8880-67c90971da5b.png)
![image](https://user-images.githubusercontent.com/6368283/48867197-852a1e80-ee29-11e8-93f3-fff7d4e340e0.png)

**Comment by theiliad** [comment]
Yes thank you @brocococonut for this. This functionality exists in the pie/donut chart components.

@dianatran18 Any thoughts?
