### ISSUE TITLE
Pie and Donut chart not behaving as expected

### ISSUE THREAD

**Issue by deandwill** [IBM/carbon-charts#46]
#### I am submitting a...

- [ ] Feature request
- [ ] Design defect
- [X] Source code defect
- [X] Demo/documentation defect
- [ ] Other

### Issue description

Not sure if this is a bug, or an error in my demo code ... but when I use either the Pie or Donut chart:

1) the background colours I've specified are not the colours displayed in the legend.

2) When I deselect a few datasets in the legend, and then click the "Random data" button, the chart and the legend are no longer in synch.

#### Steps to produce the issue

See https://codesandbox.io/s/m94mkq4n5y ... and click on "Pie Chart" or "Donut Chart"

**Comment by theiliad** [comment]
@deandwill @shinytoyrobots this bug is fixed, but we're unable to push. It seems like our NPM token is not working...
