### ISSUE TITLE
Carbon Charts for React - Stable Release for Mobile Foundation Service Dashboard

### ISSUE THREAD

**Issue by svkrish** [IBM/carbon-charts#60]
We are building our next version of the Dashboard for our service called Mobile Foundation Service which is hosted on Bluemix.   We are basing this new version on Carbon and React and have been using _carbon-components-react_

A critical aspect of our dashboard is Mobile Analytics which provides insights into mobile app usage via various charts.  Looking up the carbon-charts project it seems like the React wrapper is not complete yet.   Our requirement is line, bar and pie charts.   Is there a timeline by which we can expect a release of the React wrapper ?

**Comment by stanislavgeorgiev** [comment]
Same question but for Angular.

**Comment by zvonimirfras** [comment]
> Same question but for Angular.

https://www.npmjs.com/package/@carbon/charts-angular

**Comment by stanislavgeorgiev** [comment]
> @stanislavgeorgiev
> 
> > Same question but for Angular.
> 
> https://www.npmjs.com/package/@carbon/charts-angular

Thanks @zvonimirfras

**Comment by theiliad** [comment]
Hi @svkrish,
As we discussed on Monday, there is a `react` package present in the repo, however we have not yet released it to NPM.

In terms of timelines, when would you say your development team will need a stable release to deploy into your applications?

**Comment by svkrish** [comment]
@theiliad yes we can take a look at that package and start using it.   We are planning our release end of first week of December 2018.   I'd say we would need a stable version atleast by middle of November 2018.  Does that look possible ?

**Comment by theiliad** [comment]
Hi @svkrish. Sorry for the late reply. We're releasing `react wrappers` by the end of this month. Does that work within your timeline?

Also, you will be the first IBM team using them, so we can work closely in resolving any issues/needs you have...

**Comment by deandwill** [comment]
OK ... so how soon can we build a fully supportable "Version 1" of Carbon Charts ? ...  which teams (like 'svkrish' above ) can formally create a dependency upon (Nina can help with the paperwork in AWSOM 
 ... an IBM requirement. )

**Comment by svkrish** [comment]
@theiliad we are stretched already and have started to craft the react wrappers ourselves - we've had to show some progress :).    But then we have only started with this and we are doing this very specific to our needs.  Would be really helpful if the react wrappers are out by 3rd week of Nov.   We can shuffle somethings and wait upto that time.

**Comment by theiliad** [comment]
@svkrish ok. Are the react wrappers you made based on Carbon Charts? It might help if you send me a repo to look at. In terms of releasing the wrappers, sure we can do that.

**Comment by svkrish** [comment]
@theiliad thanks very much for letting know.    We will jump onto it rightaway.   Look forward to the codesandbox as well.

**Comment by theiliad** [comment]
@svkrish Here's the sandbox:
[![Edit Carbon Charts - React](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pppmo3ollx)

Please reach out to me directly on Slack or on here through issues, and keep me in the loop of your progress and any potential issues & concerns 🙂
