### ISSUE TITLE
Pie & Donut Label Colors can be wrong

### ISSUE THREAD

**Issue by theiliad** [IBM/carbon-charts#68]
In Pie & Donut if some of your values in the new data provided are larger than before, they get re-ordered since Pie & Donut always show the larger slices first (which is expected).

Now a bug in that functionality shows up where when the order is changed, labels take on different colors than before. If a label is re-used within the **lifetime** of a chart, it should always show the same color it was initially assigned.

**Comment by konsvasi** [comment]
Can you tell me how to reproduce this issue?
